"""
Django settings for Codepaste project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HOST_SCHEME = 'https://'
PARENT_HOST = 'codepaste.ml'
SITE_DOMAIN = HOST_SCHEME + PARENT_HOST


SECRET_KEY = os.environ.get('SECRET_KEY')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

DEBUG = os.environ.get("DEBUG") is not None

ALLOWED_HOSTS = [
    '*'
]

ADMINS = [('DarkKeks', 'darkkeks@rambler.ru')]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_hosts',
    'paste.apps.PasteConfig',
    'bot_adapter.apps.BotConfig',
    'pastebot.apps.PastebotConfig',
    'ornobot.apps.OrnobotConfig',
    'vkrepost.apps.VkRepostConfig'
]

MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware'
]

ROOT_URLCONF = 'Codepaste.urls'
ROOT_HOSTCONF = 'Codepaste.hosts'
DEFAULT_HOST = 'default'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Codepaste.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DATABASE_NAME', 'desm37nkurq8uk'),
        'USER': os.environ.get('DATABASE_USER', 'gqroltgbdavtrm'),
        'PASSWORD': os.environ.get('DATABASE_PASS', '01d678766bf1ab39e5f654e8d7669e2b701035cdc1547e75d663d9d817cdc8f8'),
        'HOST': os.environ.get('DATABASE_HOST', 'ec2-54-217-235-137.eu-west-1.compute.amazonaws.com'),
        'PORT': os.environ.get('DATABASE_PORT', '5432'),
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_L10N = True

USE_TZ = True


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    BASE_DIR + STATIC_URL,
]


PASTEBOT_TOKEN = os.environ.get('PASTEBOT_TOKEN')

CHATBASE_TOKEN = os.environ.get('CHATBASE_TOKEN')

ORNOBOT_TOKEN = os.environ.get('ORNOBOT_TOKEN')

VKREPOST_TOKEN = os.environ.get('VKREPOST_TOKEN')
VKREPOST_VK_TOKEN = os.environ.get('VKREPOST_VK_TOKEN')

