# Generated by Django 2.2.6 on 2019-10-26 22:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastebot', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('lang_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Id')),
                ('lang_text', models.CharField(max_length=255, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'paste_lang',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_alias', models.CharField(max_length=8, verbose_name='Alias')),
                ('source_lang', models.CharField(max_length=255, verbose_name='Lang')),
                ('source_bot', models.BooleanField(default=False, verbose_name='From bot')),
                ('source_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time')),
                ('source_name', models.CharField(max_length=255, verbose_name='Name')),
                ('source_source', models.TextField(verbose_name='Source')),
                ('source_bot_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pastebot.BotUser', verbose_name='Telegram user')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'db_table': 'paste_source',
            },
        ),
    ]
