# Generated by Django 2.2.6 on 2019-11-25 11:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastebot', '0001_initial'),
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='Paste',
        ),
        migrations.RenameField(
            model_name='paste',
            old_name='source_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='paste',
            old_name='source_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='paste',
            old_name='source_alias',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='paste',
            old_name='source_lang',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='paste',
            old_name='source_bot',
            new_name='created_using_bot',
        ),
        migrations.RenameField(
            model_name='paste',
            old_name='source_bot_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='paste',
            old_name='source_time',
            new_name='creation_date',
        ),
        migrations.AlterField(
            model_name='paste',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pastebot.BotUser', verbose_name='Telegram bot user'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='created_using_bot',
            field=models.BooleanField(default=False, verbose_name='Is created using telegram bot bot'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='language',
            field=models.CharField(max_length=255, verbose_name='Source language'),
        ),
        migrations.RenameModel(
            old_name='Lang',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_text',
            new_name='name',
        ),
    ]
